package com.ingramcontent.consolidated.labels.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BarcodeRules implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean usesCustomerSuppliedBarcode;
	private boolean usesBookmarcSuppliedBarcode;
	private int length;

	public BarcodeRules() {
	}

	public boolean isUsesCustomerSuppliedBarcode() {
		return this.usesCustomerSuppliedBarcode;
	}

	public void setUsesCustomerSuppliedBarcode(
			boolean usesCustomerSuppliedBarcode) {
		this.usesCustomerSuppliedBarcode = usesCustomerSuppliedBarcode;
	}

	public boolean isUsesBookmarcSuppliedBarcode() {
		return this.usesBookmarcSuppliedBarcode;
	}

	public void setUsesBookmarcSuppliedBarcode(
			boolean usesBookmarcSuppliedBarcode) {
		this.usesBookmarcSuppliedBarcode = usesBookmarcSuppliedBarcode;
	}

	public int getLength() {
		return this.length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	public BarcodeRules(boolean usesCustomerSuppliedBarcode,
			boolean usesBookmarcSuppliedBarcode, int length) {
		this.usesCustomerSuppliedBarcode = usesCustomerSuppliedBarcode;
		this.usesBookmarcSuppliedBarcode = usesBookmarcSuppliedBarcode;
		this.length = length;
	}

}