package com.ingramcontent.consolidated.labels.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BarcodeDetail implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.ingramcontent.consolidated.labels.model.OrderInformation orderInformation;
	private java.lang.Integer totalCount;

	private com.ingramcontent.consolidated.labels.model.OrderStatus orderStatus;

	private com.ingramcontent.consolidated.labels.model.BarcodeValidator barcodeValidator;

	public BarcodeDetail() {
	}

	public com.ingramcontent.consolidated.labels.model.OrderInformation getOrderInformation() {
		return this.orderInformation;
	}

	public void setOrderInformation(
			com.ingramcontent.consolidated.labels.model.OrderInformation orderInformation) {
		this.orderInformation = orderInformation;
	}

	public java.lang.Integer getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(java.lang.Integer totalCount) {
		this.totalCount = totalCount;
	}

	public com.ingramcontent.consolidated.labels.model.OrderStatus getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(
			com.ingramcontent.consolidated.labels.model.OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

	public com.ingramcontent.consolidated.labels.model.BarcodeValidator getBarcodeValidator() {
		return this.barcodeValidator;
	}

	public void setBarcodeValidator(
			com.ingramcontent.consolidated.labels.model.BarcodeValidator barcodeValidator) {
		this.barcodeValidator = barcodeValidator;
	}

	public BarcodeDetail(
			com.ingramcontent.consolidated.labels.model.OrderInformation orderInformation,
			java.lang.Integer totalCount,
			com.ingramcontent.consolidated.labels.model.OrderStatus orderStatus,
			com.ingramcontent.consolidated.labels.model.BarcodeValidator barcodeValidator) {
		this.orderInformation = orderInformation;
		this.totalCount = totalCount;
		this.orderStatus = orderStatus;
		this.barcodeValidator = barcodeValidator;
	}

}