package com.ingramcontent.consolidated.labels.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BarcodeDetail implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BarcodeDetail() {
    }




}