package com.ingramcontent.consolidated.labels.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderStatus implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean status;
	private java.lang.String messageCode;

	public OrderStatus() {
	}

	public java.lang.String getMessageCode() {
		return this.messageCode;
	}

	public void setMessageCode(java.lang.String messageCode) {
		this.messageCode = messageCode;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public OrderStatus(boolean status, java.lang.String messageCode) {
		this.status = status;
		this.messageCode = messageCode;
	}

}