package com.ingramcontent.consolidated.labels.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ToteInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.ingramcontent.consolidated.labels.model.BarcodeRules barcodeRules;

	public ToteInformation() {
	}

	public com.ingramcontent.consolidated.labels.model.BarcodeRules getBarcodeRules() {
		return this.barcodeRules;
	}

	public void setBarcodeRules(
			com.ingramcontent.consolidated.labels.model.BarcodeRules barcodeRules) {
		this.barcodeRules = barcodeRules;
	}

	public ToteInformation(
			com.ingramcontent.consolidated.labels.model.BarcodeRules barcodeRules) {
		this.barcodeRules = barcodeRules;
	}

}