package com.ingramcontent.consolidated.labels;

import com.ingramcontent.consolidated.labels.model.BarcodeDetail;
import com.ingramcontent.consolidated.labels.model.ItemStatus;

rule "If Barcode is equal to '9999'"
	when 
		barcodeDetail: BarcodeDetail(barcodeValidator != null &&
		barcodeValidator.getBarcode() == "9999")
	then
		ItemStatus status = new ItemStatus();
		status.setSuccess(false);
		status.setMessageCode("1001");
		barcodeDetail.setItemStatus(status);
	end
	
rule "If Barcode is not equal to '9999' and OrderInformation is null"
	when 
		barcodeDetail: BarcodeDetail(barcodeValidator != null &&
		barcodeValidator.getBarcode() == null && 
		barcodeValidator.getToteBarcode()
		)
	then
		ItemStatus status = new ItemStatus();
		status.setSuccess(false);
		status.setMessageCode("1001");
		barcodeDetail.setItemStatus(status);
	end	com.ingramcontent.consolidated.labels.model.BarcodeDetail( )
	
rule "If Barcode is not equal to '9999' and OrderInformation is not null and Barcode's length is not equal to BarcodeRule's length"
	when 
		barcodeDetail: BarcodeDetail(barcodeValidator != null &&
		barcodeValidator.getBarcode() != null &&
		barcodeValidator.getBarcode() != "9999" && 
		toteInformation != null && 
		toteInformation.getBarcodeRules() != null && 
		toteInformation.getBarcodeRules().isUsesCustomerSuppliedBarcode() &&
		barcodeValidator.getBarcode().length() != toteInformation.getBarcodeRules().getLength()
		)
	then
		ItemStatus status = new ItemStatus();
		status.setSuccess(false);
		status.setMessageCode("1005");
		barcodeDetail.setItemStatus(status);
	end		