package com.ingramcontent.consolidated.labels;

import com.ingramcontent.consolidated.labels.model.BarcodeDetail;
import com.ingramcontent.consolidated.labels.model.OrderStatus;

rule "update BulkItemFeedRule"
	when 
		barcodeDetail: BarcodeDetail();
	then
		
		OrderStatus status = new OrderStatus();
		status.setStatus(false);
		status.setMessageCode("100");
		barcodeDetail.setOrderStatus(status);
		
	end