package com.ingramcontent.consolidated.labels;

import com.ingramcontent.consolidated.labels.model.BarcodeDetail;
import com.ingramcontent.consolidated.labels.model.OrderStatus;

rule "If Barcode is equal to '9999'"
	when 
		barcodeDetail: BarcodeDetail(barcodeValidator != null &&
		barcodeValidator.getBarcode() == "9999")
	then
		OrderStatus status = new OrderStatus();
		status.setStatus(false);
		status.setMessageCode("1001");
		barcodeDetail.setOrderStatus(status);
	end
	
rule "If Barcode is not equal to '9999' and OrderInformation is null"
	when 
		barcodeDetail: BarcodeDetail(barcodeValidator != null &&
		barcodeValidator.getBarcode() != "9999" && 
		orderInformation == null
		)
	then
		OrderStatus status = new OrderStatus();
		status.setStatus(false);
		status.setMessageCode("1002");
		barcodeDetail.setOrderStatus(status);
	end	
	
rule "If Barcode is not equal to '9999' and OrderInformation is not null and TotalCount is equal to zero"
	when 
		barcodeDetail: BarcodeDetail(barcodeValidator != null &&
		barcodeValidator.getBarcode() != "9999" && 
		orderInformation != null && 
		orderInformation.getBarcodeRules() != null && 
		orderInformation.getBarcodeRules().getUsesCustomerSuppliedBarcode() &&
		totalCount == 0
		)
	then
		OrderStatus status = new OrderStatus();
		status.setStatus(true);
		status.setMessageCode("1003");
		barcodeDetail.setOrderStatus(status);
	end	
	
rule "If Barcode is not equal to '9999' and OrderInformation is not null and TotalCount is not equal to zero"
	when 
		barcodeDetail: BarcodeDetail(barcodeValidator != null &&
		barcodeValidator.getBarcode() != "9999" && 
		orderInformation != null && 
		orderInformation.getBarcodeRules() != null && 
		orderInformation.getBarcodeRules().getUsesCustomerSuppliedBarcode() &&
		totalCount != 0
		)
	then
		OrderStatus status = new OrderStatus();
		status.setStatus(true);
		status.setMessageCode("1004");
		barcodeDetail.setOrderStatus(status);
	end		